parameters:
    # Generate url in commands
    router.request_context.host: 'example.org'
    router.request_context.scheme: 'http'
    asset.request_context.secure: false
    router.request_context.base_url: 'my/path'
    asset.request_context.base_path: '%router.request_context.base_url%'
    # -commands

services:
    # Default section for this file only!
    _defaults:
        autowire: true

    rot13:
        class: App\Application\Service\Rot13Transformer
        tags: ['app.test2']
        # https://symfony.com/doc/5.0/service_container/expression_language.html
        # the '@=' prefix is required when using expressions for arguments in YAML files
        # when using double-quoted strings, the backslash needs to be escaped twice (see https://yaml.org/spec/1.2/spec.html#id2787109)
        # arguments: ["@=service('App\\\\Mail\\\\MailerConfiguration').getMailerMethod()"]
        arguments: 
            # - ['@=service("App\\Application\\Service\\Rot13Transformer")']
            - "@=container.hasParameter('some_param') ? parameter('some_param') : true"
            - 'both'
        # For heavy instantiation service or ocramius/proxy-manager
        lazy: true # need  ProxyManagerBridge
    
    twitter_client:
        class: App\Application\Service\TwitterClient
        autowire: true
        tags: { name: 'app.test', alias: 'app.test.alias' }
        calls:
            # the TRUE argument turns this into a wither method
            # vendor/symfony/dependency-injection/Compiler/AutowirePass.php 
            # vendor/symfony/config/Loader/FileLoader.php

            # @? make a service optional (if it doesn't exists, don't use it...)
            - [withConfiguredSerializer, ['@?serializer'], true]

            # Immutable: tell Container to use returned value of method
            - withLogger: !returns_clone ['@logger']

        # override the services to set the configurator
        # to configure a service at runtime after its instantiation
        # -> will first be passed to the TwitterServiceConfigurator::configuringService() method.
        configurator: 
            ['@App\Application\DependencyInjection\Configurator\TwitterServiceConfigurator', 'configuringService']
    
    # ###
    # Aliases HAVE to be manually declared to type-hint
    # ###
    App\Application\Service\Rot13Transformer: '@rot13'
    App\Application\Service\TwitterClient: '@twitter_client'
    App\Application\Service\TwitterClientAlias: 
        alias: '@twitter_client'
        public: false
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'

    ##########
    # Parent #
    ##########
    App\Application\Service\TwitterClientChild:
        parent: App\Application\Service\TwitterClient
        autowire: true

    # Duplicate parent service definition: NOT parent PHP inherence is mandatory
    # Except shared, abstract and tags!
    # MUST override the _defaults section to avoid ambiguity 
    other.service:
        parent: App\Application\Service\TwitterClient
        autowire: true
        
        # overrides the first argument (using the special index_N key)
        # arguments:
        #     index_0: '@rot13'

    #############
    # Anonymous service, must be defined manually
    #############
    App\Foo:
        autowire: false
        autoconfigure: false
        arguments:
            - !service
                class: App\AnonymousServiceBar
    
    App\Application\Service\FromFactoryService:
        factory: [ !service { class: App\Application\Factory\ServiceFactory }, 'createFromFactoryService' ]
        arguments: ['alphabeta']

    # ###
    # ArgumentResolver
    # ###
    App\Application\ArgumentResolver\CustomValueResolver:
        tags:
            - { name: controller.argument_value_resolver, alias: ctrl.resolv, priority: 50 }

    # DECORATOR #
    # overrides the twitter_client service but that service is still available as twitter_client.inner
    # twitter_client_decorated:
    #     decorates: twitter_client
    #     decoration_inner_name: App\DecoratingMailer.wooz
    #     decoration_priority: 5
    #     decoration_on_invalid: ignore
