FROM postgres:13.2
# debian, "lsb_release -sc"=buster

# Postgres
# RUN apt-get install -y postgresql-11 postgresql-server-dev-11

# PGadmin
# RUN sed -ie "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/11/main/postgresql.conf
# RUN sed -ie "s#127.0.0.1/32#0.0.0.0/0#" /etc/postgresql/11/main/pg_hba.conf


### INIT entrypoint ###
#service postgresql start
# change password
#echo psql -c \"alter user postgres with password \'${MYPGPASSWORD}\'\" > /tmp/pg.tmp
#su postgres < /tmp/pg.tmp
#su postgres -c "createdb ${MYPGDATABASE}"
###
