# config/packages/knp_menu.yaml

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: my_knp_menu.html.twig

    #  if true, enables the helper for PHP templates
    templating: false

    # the renderer to use, list is also available by default
    default_renderer: twig

services:
    app.menu_builder:
        class: App\Application\Service\MenuBuilder
        arguments: ["@knp_menu.factory", "@router"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createDocMenu, alias: doc } # The alias is what is used to retrieve the menu