# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    #
    # @see https://symfony.com/doc/5.0/session.html
    session:
        enabled: true
        cookie_secure: auto
        cookie_samesite: lax

        # session in database 2/2 (service.yml)
        #handler_id: null # native PHP session
        #handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        #handler_id: 'session.handler.native_file'
        handler_id: App\Application\Session\CustomSessionProxy

        # allow Symfony to work with a session started outside of the Symfony HttpFoundation component
        #storage_id: session.storage.php_bridge
        storage_id: App\Application\Session\CustomSessionStorage

    esi: true # { enabled: true }
    
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:

    default_locale: en
    error_controller: App\Application\Controller\Error\AppErrorController

    router:
        strict_requirements: true
    
    # for twig fragment
    fragments: { path: /_fragments_update }

# secrets:
    #vault_directory: '%kernel.project_dir%/config/secrets/%kernel.environment%'
    #local_dotenv_file: '%kernel.project_dir%/.env.%kernel.environment%.local'
    #decryption_env_var: 'base64:default::SYMFONY_DECRYPTION_SECRET'

    ########
    # FORM #
    ########
    csrf_protection: ~ # _token in forms
