twig:
    default_path: '%kernel.project_dir%/templates'
    
    form_themes: 
        - form_div_layout.html.twig # default
    #form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    
    number_format:
        decimals: 0
        decimal_point: .
        thousands_separator: ','

    paths:
        'templates/architecture': ~

    globals:
        ga_tracking: 'from_twig.globals'
        tweeting: '@twitter_client'