#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /components

contact:
    path: 
        en: /contact
        nl: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    # context is a RequestContext object
    condition: "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"
    defaults:
        path: /components
    
myapp:
    path: /blog/{page<\d+>?default_value} # ("\d+" required, and "default_value" provided)
    controller: App\Application\Controller\AdvancedController::message
    methods: GET|HEAD
    requirements:
        # \p reference PCRE Unicode char 
        # https://www.php.net/manual/en/regexp.reference.unicode.php 
        page: \d+\p{Lu}? 
    defaults:
        page: 1
    options:
        utf8: true # "." match any utf8 char

# ROUTE LOADER #
route_loader:
    # loads routes from the given routing file stored in some bundle
    resource: '@AppMyBundle/Resources/config/' # routing.yaml'
    type:     annotation # directory

custom_routes_loader_service:
    resource: 'custom_route_loader_service::loadMyRoutes'
    type: service
    trailing_slash_on_root: true
    utf8: true

custom_routes_loader:
    resource: . # unneeded
    type: my_extra