#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /components

static: 
  path: /static 
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: base.html.twig
    maxAge:    86400
    sharedAge: 86400

contact:
    path: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    condition: "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"
    defaults:
      path: /components
    
myapp:
    path: /blog/{page}
    controller: App\Application\Controller\AdvancedController::message
    requirements:
        page: \d+
    defaults:
        page: 1