FROM rabbitmq:3.8

# IMAGE: bitnami/rabbitmq

# Rabbitmq with erlang 22
# https://www.rabbitmq.com/install-debian.html#apt
# RUN apt-get install -y curl gnupg apt-transport-https
# RUN curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | apt-key add -
# RUN echo "deb https://dl.bintray.com/rabbitmq-erlang/debian buster erlang" > /etc/apt/sources.list.d/bintray.rabbitmq.list
# RUN echo "deb https://dl.bintray.com/rabbitmq/debian buster main" >> /etc/apt/sources.list.d/bintray.rabbitmq.list
# RUN apt-get update -y