#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController'
  defaults:
    path: /all

redirect:
    path: /old-path
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController'
    defaults:
        path: /new-path

static: 
  path: /static 
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: base.html.twig
    maxAge:    86400
    sharedAge: 86400