#index:
#    path: /
#    controller: App\Controller\DefaultController::index

redirect:
    path: /old-path
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController'
    defaults:
        path: /new-path