services:
    App\Domain\Manager\:
        resource: '../src/Domain/Manager/'
        autowire: true
        autoconfigure: true
        public: true

    # Testing
    #test.App\Test\SomeTestHelper:
        # id of the private service
        #alias: 'My\Private\Service'
        #public: true