# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: services/knp/knp_menu.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    a: "%%b%%" # will output "%b%"
    b: "%a%%"  # will output "%b%%"
    devhost: docker

services:
    # default configuration for services in *this* file
    _defaults:
        # Autowiring will automatically call any method with the @required annotation above it (setter)
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # Autowire interface
    _instanceof:
        App\Domain\Service\ServiceDomainInterface:
            public: false
            tags: ['service.my_tag']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #
    # Resource and exclude can be any GLOB pattern
    App\:
        # namespace: MyNamespace\
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Tests/'
            # - '../src/DependencyInjection/'
            # - '../src/Entity/'

            #####################
            # manually imported #
            #####################
            - '../src/Application/Service/'
            - '../src/Domain/**/*Handler'
            - '../src/Infrastructure/'

            ################
            # Not imported #
            ################
            - '../src/Application/Response.php'
            - '../src/Domain/Message/*'
            - '../src/Domain/Model/*'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Application\Controller\:
        # namespace: MyNamespace2\
        resource: '../src/Application/Controller/'
        exclude: '../src/Application/Controller/Error/'
        tags: ['controller.service_arguments']
        bind:
            # for any $logger argument, pass this specific service
            $bind_from_service_logger: '@monolog.logger.doctrine'
            Psr\Log\LoggerInterface $httpClientLogger: '@monolog.logger.http_client'
            string $myCustomData: 'from services.yaml'
            iterable $rules: !tagged_iterator 'service.my_tag'

    # Bundle for github/phpext playground
    Bundle\ExtBundleController:
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
