##########
# GITHUB #
##########

# DOC
# https://github.com/actions/starter-workflows/

name: Sym-doc

on:
  push:
    branches: [ main ]

###
# Jobs
###
jobs:
  #########
  # TESTS #
  #########
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    # Php, composer, ext, xdebug
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: xdebug
        extensions: |
          curl, gd, intl, mbstring, pdo_sqlite, \
          opcache, sqlite3, sockets, sodium, xsl, zip
        php-version: "7.4"

    - name: Symfony cli
      run: make symfony-bin

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      # env:
      #   APP_ENV: prod # post-install-cmd
      run: composer install --prefer-dist --no-cache --no-progress

    - name: Tests
      run: vendor/bin/phpunit
